FROM node:22-alpine AS builder
WORKDIR /app
COPY . .
ENV VITE_API_URL=/api/v1
RUN npm install && npm run build

FROM nginx:latest
COPY --from=builder /app/dist /usr/share/nginx/html
COPY ./nginx/k8s/nginx.conf /etc/nginx/nginx.conf