apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
  namespace: goboard
spec:
  selector:
    app: 
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
  
