apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: goboard
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: rakjija/goboard-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USER
              value: goboard-user
            - name: MYSQL_PASSWORD
              value: goboard-pass
            - name: MYSQL_DATABASE
              value: goboard
            - name: OBSERVER_ENDPOINT
              value: http://observer:9000
