services:
  frontend:
    container_name: goboard-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.compose
    ports:
      - '3000:80'
    depends_on:
      - backend

  backend:
    container_name: goboard-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8080:${BACKEND_PORT}'
    env_file:
      - .env
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/healthz']
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - mysql
    restart: unless-stopped
    volumes:
      - .env:/app/.env:ro
      - ./backend/logs:/app/logs/backend

  mysql:
    container_name: goboard-mysql
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf:ro
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped

  prometheus:
    container_name: goboard-prometheus
    image: prom/prometheus:latest
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'

  loki:
    container_name: goboard-loki
    image: grafana/loki:latest
    ports:
      - '3100:3100'
    volumes:
      - ./monitoring/loki-config.yaml:/etc/loki/local-config.yml
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    container_name: goboard-promtail
    image: grafana/promtail:latest
    volumes:
      - ./monitoring/promtail-config.yaml:/etc/promtail/config.yml
      - ./backend/logs:/app/logs/backend
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

  grafana:
    container_name: goboard-grafana
    image: grafana/grafana:latest
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - '3001:3000'
    depends_on:
      - prometheus
      - loki

volumes:
  mysql_data:
  grafana-data:
