global:
  scrape_interval: 5s # 메트릭 수집 주기

scrape_configs:
  - job_name: "log-service"
    static_configs:
      - targets: ["log-service:8080"]

  - job_name: "promtail"
    static_configs:
      - targets: ["promtail:9080"] # Promtail은 9080 포트에서 /metrics 제공
