apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: goboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: goboard
            - name: MYSQL_USER
              value: goboard-user
            - name: MYSQL_PASSWORD
              value: goboard-pass
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: goboard
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
