{
 "title": "GoBoard Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum(backend_requests_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg(backend_request_duration_seconds_sum / backend_request_duration_seconds_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests by Method",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (method) (backend_requests_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests per Second (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (code) (rate(backend_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"backend\"}"
    }
   ]
  },
  {
   "title": "Total Requests by URL",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (url) (backend_requests_total)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}