server:
  http_listen_port: 9000
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://goboard-loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: backend
    static_configs:
      - targets:
          - localhost
        labels:
          job: backend
          __path__: /app/logs/backend/*.log
