apiVersion: apps/v1
kind: Deployment
metadata:
  name: observer
  namespace: goboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: observer
  template:
    metadata:
      labels:
        app: observer
    spec:
      containers:
        - name: observer
          image: rakjija/goboard-observer:latest
          ports:
            - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: observer
  namespace: goboard
spec:
  selector:
    app: observer
  ports:
    - port: 5601
      targetPort: 9000
