replicaCount: 2

image:
  repository: rakjija/goboard-backend
  tag: v1.1.6
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

containerPort: 8080

env:
  - name: MYSQL_HOST
    value: mysql
  - name: MYSQL_PORT
    value: "3306"
  - name: MYSQL_USER
    value: goboard-user
  - name: MYSQL_PASSWORD
    value: goboard-pass
  - name: MYSQL_DATABASE
    value: goboard
