// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "rakjija",
            "url": "https://github.com/rakjija/bot-trap"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/healthz": {
            "get": {
                "tags": [
                    "system"
                ],
                "summary": "헬스 체크",
                "responses": {
                    "200": {
                        "description": "서버 정상 동작 확인",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/logs": {
            "post": {
                "description": "JSON 형식의 로그를 수신하고 저장 (stdout + metrics)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "logs"
                ],
                "summary": "로그 저장",
                "parameters": [
                    {
                        "description": "로그 내용",
                        "name": "log",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_rakjija_bot-trap_internal_model.LogPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "성공 응답",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "잘못된 요청",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "서버 에러",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_rakjija_bot-trap_internal_model.LogPayload": {
            "description": "JSON 형식의 로그를 수신하고 저장합니다 (stdout + metrics)",
            "type": "object",
            "required": [
                "ip",
                "message",
                "path"
            ],
            "properties": {
                "ip": {
                    "description": "클라이언트의 IP 주소",
                    "type": "string",
                    "example": "192.168.0.1"
                },
                "message": {
                    "description": "의심되는 메시지",
                    "type": "string",
                    "example": "SQL injection attempt"
                },
                "path": {
                    "description": "접근한 경로",
                    "type": "string",
                    "example": "/admin"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "BotTrap API",
	Description:      "백엔드 이상 행동 탐지 시스템 API 문서입니다.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
