name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write  # GitHub Release 생성을 위한 권한

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.2'

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: go test ./...

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image with tag
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            rakjija/bottrap:${{ github.ref_name }}
            rakjija/bottrap:latest

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true

      - name: Slack Notification
        if: ${{ always() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: GitHub Action - ${{ github.workflow }}
          SLACK_MESSAGE: |
            🔔 *${{ github.repository }}*
            ▸ Tag: `${{ github.ref_name }}`
            ▸ Status: *${{ job.status }}*
            ▸ Action: `${{ github.workflow }}`