name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write # GitHub Release 생성을 위한 권한

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.2'

      - name: Download dependencies (backend)
        run: |
          cd backend
          go mod download

      - name: Run backend tests
        run: |
          cd backend
          go test ./...

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/goboard-backend:${{ github.ref_name }}
            ${{ secrets.DOCKER_USERNAME }}/goboard-backend:latest

      - name: Build and push observer image
        uses: docker/build-push-action@v5
        with:
          context: ./observer
          file: ./observer/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/goboard-observer:${{ github.ref_name }}
            ${{ secrets.DOCKER_USERNAME }}/goboard-observer:latest

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true

      - name: Slack Notification
        if: ${{ always() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: Docker Image Release - ${{ github.workflow }}
          SLACK_MESSAGE: |
            🐳 *GoBoard Docker Release*
            - Repository: *${{ github.repository }}*
            - Tag: `${{ github.ref_name }}`
            ▸ Backend: `${{ secrets.DOCKER_USERNAME }}/goboard-backend`
            ▸ Observer: `${{ secrets.DOCKER_USERNAME }}/goboard-observer`
            ▸ Status: *${{ job.status }}*
