name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 모든 커밋 히스토리를 가져와야 git push 가능

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.2'

      - name: Download dependencies (backend)
        run: |
          cd backend
          go mod download

      - name: Run backend tests
        run: |
          cd backend
          go test ./...

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/goboard-backend:${{ github.ref_name }}
            ${{ secrets.DOCKER_USERNAME }}/goboard-backend:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile.k8s
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/goboard-frontend:${{ github.ref_name }}
            ${{ secrets.DOCKER_USERNAME }}/goboard-frontend:latest

      - name: Check out main branch
        run: |
          git checkout main

      - name: Update Helm values.yaml (frontend/backend)
        run: |
          sed -i "s/tag: .*/tag: ${GITHUB_REF_NAME}/" helm/frontend/values.yaml
          sed -i "s/tag: .*/tag: ${GITHUB_REF_NAME}/" helm/backend/values.yaml

      - name: Commit updated values.yaml
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add helm/frontend/values.yaml helm/backend/values.yaml
          git commit -m "chore: update image tags to ${{ github.ref_name }}"
          git push

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true

      - name: Slack Notification
        if: ${{ always() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: Docker Image Release - ${{ github.workflow }}
          SLACK_MESSAGE: |
            🐳 *GoBoard Docker Release*
            - Repository: *${{ github.repository }}*
            - Tag: `${{ github.ref_name }}`
            ▸ Backend: `${{ secrets.DOCKER_USERNAME }}/goboard-backend`
            ▸ Frontend: `${{ secrets.DOCKER_USERNAME }}/goboard-frontend`
            ▸ Status: *${{ job.status }}*
